version: '3.7'

services:
  pprldemos:
    build:
      context: .
      args:
        #PPIRL_API: /api/ppirl
        BLOOMFILTER_API: https://run.mocky.io/v3/1acd51c3-9f61-4e9a-a235-51986d59d137
    ports:
      - "2000:80"